# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Cleanup caches

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    permissions:
      actions: write
      contents: read
    uses: dallay/common-actions/.github/workflows/cleanup-cache.yml@69060250307677655136ca88c70a2f77cb4153b2 # v2.2.4
    secrets: inherit
