# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Cleanup caches

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    permissions:
      actions: write
      contents: read
    uses: dallay/common-actions/.github/workflows/cleanup-cache.yml@6548f0dfaad9e40648cd56e85566e5bc2d707dfb # v2.2.2
    secrets: inherit
