# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Cleanup caches

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    permissions:
      actions: write
      contents: read
    uses: dallay/common-actions/.github/workflows/cleanup-cache.yml@8aaf32edb1b70941a3f8889b47af1a7fd47e3a2c # v2.2.1
    secrets: inherit
