# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Contributor Report

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

permissions:
  contents: read
  pull-requests: write

jobs:
  report:
    uses: dallay/common-actions/.github/workflows/contributor-report.yml@0f8de7c46309882e873a878e1fcc636bf56ad586 # v1.2.0
    with:
      trusted-users: dependabot[bot],renovate[bot],github-copilot[bot],github-actions[bot],codecov[bot],sonarcloud[bot],dallay-bot[bot]
    secrets: inherit
