# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Contributor Report

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

permissions:
  contents: read
  pull-requests: write

jobs:
  report:
    uses: dallay/common-actions/.github/workflows/contributor-report.yml@6ecd716dcfb6a9e8a9c494d1eac210cc1d73d75f # v2.0.0
    with:
      trusted-users: dependabot[bot],renovate[bot],github-copilot[bot],github-actions[bot],codecov[bot],sonarcloud[bot],dallay-bot[bot]
    secrets: inherit
