# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Sync Github labels

on:
  push:
    branches:
      - main
    paths:
      - ".github/config/labels.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  sync-labels:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1
          sparse-checkout: ".github/config/labels.yml"

      - name: ☯ Sync labels
        uses: EndBug/label-sync@52074158190acb45f3077f9099fea818aa43f97a # v2.3.3
        with:
          config-file: ".github/config/labels.yml"
          delete-other-labels: true
          token: ${{ secrets.GITHUB_TOKEN }}
