# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Greetings

on: [pull_request_target, issues]

jobs:
  greet:
    permissions:
      issues: write
      pull-requests: write
    uses: dallay/common-actions/.github/workflows/greetings.yml@8aaf32edb1b70941a3f8889b47af1a7fd47e3a2c # v2.2.1
    secrets: inherit
