# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Greetings

on: [pull_request_target, issues]

permissions:
  issues: write
  pull-requests: write

jobs:
  greet:
    uses: dallay/common-actions/.github/workflows/greetings.yml@6ecd716dcfb6a9e8a9c494d1eac210cc1d73d75f # v2.0.0
    secrets: inherit
