# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Link Checker

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lychee:
    name: Check links with lychee
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: ✈ Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: 🔗 Restore lychee cache
        uses: actions/cache@0c907a75c2c80ebcb7f088228285e798b750cf8f # v4.2.1
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: 🔗 Check links
        id: lychee
        uses: lycheeverse/lychee-action@8646ba30535128ac92d33dfc9133794bfdd9b411 # v2.8.0
        with:
          args: --config ./lychee.toml --no-progress .
          output: ./lychee/out.md
          fail: false

      - name: 📝 Prepare report
        if: steps.lychee.outputs.exit_code != 0
        run: |
          mkdir -p .github/lychee
          cp ./lychee/out.md .github/lychee/report.md

      - name: 💾 Create PR with report
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "auto-pr/lychee-broken-links"
          commit-message: "chore: update lychee link report [skip ci]"
          title: "chore: update lychee link report"
          labels: |
            pr|chore
            broken-links
          body: |
            ## Summary

            Automated lychee report for broken links.

      - name: 💾 Save lychee cache
        uses: actions/cache/save@0c907a75c2c80ebcb7f088228285e798b750cf8f # v4.2.1
        if: always()
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
