# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: PR Size Labeler

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  label:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    uses: dallay/common-actions/.github/workflows/pr-size-labeler.yml@6548f0dfaad9e40648cd56e85566e5bc2d707dfb # v2.2.2
