# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: PR Size Labeler

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  label:
    uses: dallay/common-actions/.github/workflows/pr-size-labeler.yml@0f8de7c46309882e873a878e1fcc636bf56ad586 # v1.2.0
    secrets: inherit
