# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: PR Size Labeler

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  label:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    uses: dallay/common-actions/.github/workflows/pr-size-labeler.yml@69060250307677655136ca88c70a2f77cb4153b2 # v2.2.4
