# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: PR Checks

on:
  push:
    branches:
      - "**"
    tags:
      - "!**"
  pull_request:
    branches:
      - main
      - minor
      - fix/**
      - feat/**
      - patch/**
  workflow_dispatch:

concurrency:
  # see: https://stackoverflow.com/a/72408109/30654190
  group: ${{ github.workflow }}-${{ github.event.issue.number || github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read

    steps:
      - name: ✈ Checkout default branch
        if: github.event_name != 'issue_comment'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: ✏ Validate commit messages
        if: >
          github.event.pull_request.user.login != 'github-actions[bot]' &&
          github.event.pull_request.user.login != 'dependabot[bot]' &&
          github.event.pull_request.user.login != 'renovate[bot]'
        run: |
          chmod +x .github/workflows/shell/check-commit-msg.sh
          .github/workflows/shell/check-commit-msg.sh

      #      - name: 🔀 Merge target branch into PR branch
      #        if: github.event_name == 'pull_request' || github.event_name == 'issue_comment'
      #        run: |
      #          git fetch origin ${{ github.base_ref }}:target-branch
      #          git merge --no-ff target-branch

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
        with:
          version: 10

      - name: 📦 Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: "24"
          cache: "pnpm"
          cache-dependency-path: |
            pnpm-lock.yaml
            clients/web/pnpm-lock.yaml
            clients/web/apps/docs/pnpm-lock.yaml
            clients/web/apps/marketing/pnpm-lock.yaml

      - name: ☕ Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: "25"
          distribution: "corretto"

      - name: 🐘 Setup Gradle
        uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2
        with:
          gradle-version: wrapper
          cache-read-only: false

      - name: 🔧 Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: 🔧 Show Gradle version
        run: ./gradlew --version

      #      - name: 🦆 Run Actionlint
      #        run: ./gradlew runActionlint

      - name: 🔒 Check locks
        if: >
          github.event.pull_request.user.login != 'github-actions[bot]' &&
          github.event.pull_request.user.login != 'dependabot[bot]' &&
          github.event.pull_request.user.login != 'renovate[bot]'
        run: ./gradlew checkLocksAll --no-parallel

      - name: 🏗 Run main checks
        run: ./gradlew check

      - name: 🛠 Generate CycloneDX BOM
        if: github.event_name != 'pull_request'
        run: ./gradlew cyclonedxBom --no-configuration-cache

      - name: 📈 Generate Code Coverage Report
        if: github.event_name != 'pull_request'
        run: ./gradlew testCodeCoverageReport testCoverageAllWebApps

      - name: 📤 Upload Kotlin/Rust coverage to Codecov
        if: github.event_name != 'pull_request' && github.actor != 'dependabot[bot]'
        uses: codecov/codecov-action@1af58845a975a7985b0beb0cbe6fbbb71a41dbad # v5.5.3
        with:
          fail_ci_if_error: true
          verbose: true
          flags: rust,kotlin
          files: ./gradle/aggregation/build/reports/coverage/coverage.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: 📤 Upload Web coverage to Codecov
        if: github.event_name != 'pull_request' && github.actor != 'dependabot[bot]'
        uses: codecov/codecov-action@1af58845a975a7985b0beb0cbe6fbbb71a41dbad # v5.5.3
        with:
          fail_ci_if_error: true
          verbose: true
          flags: web
          directory: ./clients/web/apps
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
