# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint PR title

on:
  pull_request_target:
    types: [opened, edited, synchronize]

permissions:
  pull-requests: write

jobs:
  lint:
    uses: dallay/common-actions/.github/workflows/semantic-pr.yml@e77aee209c07cd031e1fc6a3f275df774b4685a2 # v1.1.0
    secrets: inherit
