# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint PR title

on:
  pull_request_target:
    types: [opened, edited, synchronize]

permissions:
  pull-requests: write

jobs:
  lint:
    uses: dallay/common-actions/.github/workflows/semantic-pr.yml@0f8de7c46309882e873a878e1fcc636bf56ad586 # v1.2.0
    secrets: inherit
