# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Stale

on:
  schedule:
    - cron: "0 2 * * *"

jobs:
  stale:
    permissions:
      issues: write
      pull-requests: write
    uses: dallay/common-actions/.github/workflows/stale.yml@8aaf32edb1b70941a3f8889b47af1a7fd47e3a2c # v2.2.1
    secrets: inherit
