# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Stale

on:
  schedule:
    - cron: "0 2 * * *"

jobs:
  stale:
    permissions:
      issues: write
      pull-requests: write
    uses: dallay/common-actions/.github/workflows/stale.yml@6ecd716dcfb6a9e8a9c494d1eac210cc1d73d75f # v2.0.0
    secrets: inherit
