# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Stale

on:
  schedule:
    - cron: "0 2 * * *"

jobs:
  stale:
    permissions:
      issues: write
      pull-requests: write
    uses: dallay/common-actions/.github/workflows/stale.yml@87129475c06d9f3354d398426926ba4345a4644d # v2.2.3
    secrets: inherit
